In [5]:
import numpy as np
data1=[100,300,200,False,400,True,500]
print(data1,len(data1),type(data1))
arr1=np.array(data1)
print(arr1,len(arr1),type(arr1))

[100, 300, 200, False, 400, True, 500] 7 <class 'list'>
[100 300 200   0 400   1 500] 7 <class 'numpy.ndarray'>


In [7]:
import numpy as np
data1=[100,300,200.5,False,400,True,500]
print(data1,len(data1),type(data1))
arr1=np.array(data1)
print(arr1,len(arr1),type(arr1))

[100, 300, 200.5, False, 400, True, 500] 7 <class 'list'>
[100.  300.  200.5   0.  400.    1.  500. ] 7 <class 'numpy.ndarray'>


In [11]:
print(list(range(1,10)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [21]:
print(list[range(1,5),range(5,9)]) #creates a range object representing the sequence of numbers from 1 to 4 (the end value 5 is not included).
print([list(range(1, 5)), list(range(5, 9))])

data2=[[1,2,3,4],[5,6,7,8]] #data2 is a list of lists, where each sublist represents a row of numbers: [[1, 2, 3, 4], [5, 6, 7, 8]].
arr2=np.array(data2) #NumPy recognizes this as a 2D array (or matrix), where each inner list becomes a row of the array.

print(data2,type(data2))
print(arr2,type(arr2))

list[range(1, 5), range(5, 9)]
[[1, 2, 3, 4], [5, 6, 7, 8]]
[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [23]:
for x in np.nditer(arr2): #np.nditer(arr2) creates an iterator object that iterates over each element of the NumPy array arr2.
    print (x, end = ", ")
    #Flattening is the process of converting a multi-dimensional array (like a 2D matrix or a 3D array) into a one-dimensional (1D) array.

1, 2, 3, 4, 5, 6, 7, 8, 

In [25]:
print (arr1, arr1.shape, type(arr1)) #The shape is a tuple that indicates the size of the array in each dimension.
print (arr2, arr2.shape, type(arr2)) #indicating it is a 2D array with 2 rows and 4 columns
data1 = arr1.tolist() #converts the NumPy array arr1 to a Python list.
print (data1, type(data1))
data2 = arr2.tolist()
print (data2, type(data2))

[100.  300.  200.5   0.  400.    1.  500. ] (7,) <class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]] (2, 4) <class 'numpy.ndarray'>
[100.0, 300.0, 200.5, 0.0, 400.0, 1.0, 500.0] <class 'list'>
[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>


In [29]:
print (arr1, type(arr1))
print (len(arr1), arr1.shape, arr1.ndim, arr1.size, arr1.dtype) #arr1.ndim: Returns the number of dimensions of arr1. For arr1, ndim would be 1 because it's a 1D array.
print (arr2, type(arr2))
print (len(arr2), arr2.shape, arr2.ndim, arr2.size, arr2.dtype)

[100.  300.  200.5   0.  400.    1.  500. ] <class 'numpy.ndarray'>
7 (7,) 1 7 float64
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
2 (2, 4) 2 8 int32


In [31]:

print (np.zeros(10)) #This creates a 1-dimensional array with 10 elements, all initialized to 0.0.
print (np.zeros(10).astype(int))  #astype(int) casts the elements of the array from their default float64 type to int.

print (np.zeros((2, 5)))
print (np.zeros((2, 5)).astype(int))
print (np.zeros(10).reshape(2, 5)) #Reshapes an array to the specified dimensions without changing its data.
print (np.zeros(10).reshape(5, 2).astype(int))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [33]:

arr3 = np.array(range(10)).reshape(5, 2) #reshape(5, 2) reshapes this 1D array into a 2D array with 5 rows and 2 columns
print (arr3, arr3.shape)
arr3 = np.arange(10).reshape(5, 2) #np.arange(10) creates a NumPy array with values from 0 to 9: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print (arr3, arr3.shape)
print (arr3.T)
print (arr3.transpose())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)
[[0 2 4 6 8]
 [1 3 5 7 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [35]:
matrix = np.arange(10, dtype = float).reshape((2, 5))
print (matrix)
print("Stored in C-style order (Row Major):")
cmatrix = matrix.copy(order = 'C') #matrix.copy(order='C') creates a copy of matrix with C-style order (row-major order). In C-style order, the array is stored row-by-row in memory.

print (cmatrix)
for x in np.nditer(cmatrix):
    print (x, end = ", ")

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
Stored in C-style order (Row Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 

In [39]:
matrix = np.arange(10, dtype = np.int8) #np.arange(10, dtype=np.int8) creates an array with values from 0 to 9 using 8-bit integers.
print (matrix, len(matrix))
matrix = np.append(matrix, [10, 11, 12])
print (matrix, len(matrix))
matrix = np.insert(matrix, 3, [13, 14, 15])
print (matrix, len(matrix))
matrix = np.delete(matrix, [5, 6, 7])
print (matrix,len(matrix))
matrix = np.sort(matrix)
print (matrix)
print (-matrix)
matrix = -np.sort(-matrix)
print (matrix)


[0 1 2 3 4 5 6 7 8 9] 10
[ 0  1  2  3  4  5  6  7  8  9 10 11 12] 13
[ 0  1  2 13 14 15  3  4  5  6  7  8  9 10 11 12] 16
[ 0  1  2 13 14  5  6  7  8  9 10 11 12] 13
[ 0  1  2  5  6  7  8  9 10 11 12 13 14]
[  0  -1  -2  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14]
[14 13 12 11 10  9  8  7  6  5  2  1  0]


In [41]:

a = np.array([[1, 2], [3, 4]])
print ("First Array:")
print (a)
b = np.array([[5, 6], [7, 8]])
print ("Second Array:")
print (b)
# both the arrays are of the same dimensions
print ("Joining these two arrays along axis 0") #Joining Along Axis 0: Stacks the arrays vertically, resulting in a larger array with combined rows.
print (np.concatenate((a, b)))
print ("Joining these two arrays along axis 1") #Joining Along Axis 1: Stacks the arrays horizontally, resulting in a larger array with combined columns.
print (np.concatenate((a, b), axis = 1))

First Array:
[[1 2]
 [3 4]]
Second Array:
[[5 6]
 [7 8]]
Joining these two arrays along axis 0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Joining these two arrays along axis 1
[[1 2 5 6]
 [3 4 7 8]]


In [43]:

a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print (a, a.shape, a.ndim)
a = a.reshape(1, -1) #reshape(1, -1) reshapes the array into a 2D array with 1 row and as many columns as needed to fit the data.
#-1 allows NumPy to automatically calculate the number of columns
print (a, a.shape, a.ndim)
a = a.reshape(1, 1, -1)
#reshape(1, 1, -1) reshapes the array into a 3D array with 1 depth, 1 row, and as many columns as needed to fit the data.
print (a, a.shape, a.ndim)
a = a.reshape(1, -1)
print (a, a.shape, a.ndim)
a = a.reshape(-1)
#reshape(-1) flattens the array back to a 1D array. -1 means to flatten the array into a single dimension.
print (a, a.shape, a.ndim)

[10 20 30 40 50 60 70 80] (8,) 1
[[10 20 30 40 50 60 70 80]] (1, 8) 2
[[[10 20 30 40 50 60 70 80]]] (1, 1, 8) 3
[[10 20 30 40 50 60 70 80]] (1, 8) 2
[10 20 30 40 50 60 70 80] (8,) 1


In [49]:

a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print (a, a.shape, a.ndim)
a = a.reshape(2, -1, 2)
#Target Shape: You want to reshape it into (2, -1, 2):

# 2: This is the number of blocks (or layers) you want.
# -1: This tells NumPy to figure out the size of this dimension automatically based on the other dimensions.
# 2: This is the number of columns you want in each row.
# Determine the Size of the -1 Dimension:

# You need to figure out how many rows fit into each block.

# To do this, use the formula:

# Number of elements
# =
# First dimension size
# ×
# Size of the second dimension
# ×
# Last dimension size
# Number of elements=First dimension size×Size of the second dimension×Last dimension size
# Substituting the known values:

# 8
# =
# 2
# ×
# Size of the second dimension
# ×
# 2
# 8=2×Size of the second dimension×2
# Solving for the Size of the second dimension:

# Size of the second dimension
# =
# 8
# 2
# ×
# 2
# =
# 2
# #Size of the second dimension= 
# 2×2
# 8
# ​
# # =2
print (a, a.shape, a.ndim)

[10 20 30 40 50 60 70 80] (8,) 1
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]] (2, 2, 2) 3


In [51]:
arr = np.arange(10)
print (arr, arr[5:8])
arr[5:8] = 20
print (arr)
arr_copy = arr[5: 8].copy() #arr_copy = arr[5:8].copy() creates a new copy of the slice [20, 20, 20]
print (arr_copy)
arr_copy[:] = 90
print (arr_copy, arr, type(arr_copy))

[0 1 2 3 4 5 6 7 8 9] [5 6 7]
[ 0  1  2  3  4 20 20 20  8  9]
[20 20 20]
[90 90 90] [ 0  1  2  3  4 20 20 20  8  9] <class 'numpy.ndarray'>
